// Mock data for SOIC platform
export const SOIC_DATA = {
  courses: [
    {
      id: 'c1',
      title: 'Filmmaking Diploma',
      titleAr: 'دبلومة صناعة الأفلام',
      category: 'Diploma',
      level: 'Beginner → Pro',
      instructor: 'SOIC Faculty + Industry Pros',
      instructorId: 'i1',
      price: 8400,
      originalPrice: 12000,
      duration: '3 months',
      lectures: 36,
      enrolled: 142,
      rating: 4.9,
      tag: '30% OFF · Katameya Branch',
      startDate: '2025-12-08',
      status: 'live',
      cover: 'DIRECTING · CINEMATOGRAPHY · EDITING · SCREENWRITING',
      tint: '#2d4ee0',
      coverImage: 'https://scontent-lga3-1.xx.fbcdn.net/v/t39.30808-6/605523108_122266350338036919_3950300809331463090_n.jpg?stp=cp6_dst-jpg_s590x590_tt6&_nc_cat=108&ccb=1-7&_nc_sid=833d8c&_nc_ohc=K3mzlMu2hTcQ7kNvwFhzPxD&_nc_oc=AdrJ2049sM6QKb6SrTkj36WT3Gjcmo1QV1cn95u1PhBXUEMJlWbaz8NhvCGb1WkIJ3g&_nc_zt=23&_nc_ht=scontent-lga3-1.xx&_nc_gid=torgiEbb5XGD2Dd3TsLu5A&_nc_ss=72289&oh=00_Af51sGd_mz7fVjr_uTOyn9p7UB6Jt0bnVRn-yyDIzX4QOA&oe=6A1CDE04',
      description: 'A 3-month intensive diploma covering everything you need to start working in the cinema industry. You\u2019ll learn under faculty from the Cinema Institute and industry professionals actively working on films, ads, and TV series — real teaching from inside the industry. Graduates receive a SOIC-issued certificate, eligibility to apply to the Egyptian Film Professions Syndicate, hands-on practical training, and complete a real graduation project. 30% discount currently active to celebrate the new Katameya Gardens branch.',
      descriptionAr: 'دبلومة مكثفة لمدة 3 شهور تغطي كل اللي محتاجه عشان تبدأ شغلك في صناعة السينما. هتتعلم على إيد دكاترة من معهد السينما وأساتذة شغالين فعلًا في السوق على أفلام وإعلانات ومسلسلات — تعليم حقيقي من قلب الصناعة. بتحصل بعدها على شهادة معتمدة من SOIC، فرصة للانضمام لنقابة المهن السينمائية، تطبيق عملي ومشروع تخرج حقيقي. خصم 30% حاليًا بمناسبة افتتاح فرع القطامية جاردنز.',
      locations: ['Katameya Gardens Club (new branch)', 'Zahraa El Maadi'],
      includes: ['SOIC certificate', 'Film Professions Syndicate eligibility', 'Practical on-set training', 'Graduation short film'],
      modules: [
        { title: 'Cinematic Directing', titleAr: 'الإخراج السينمائي', lessons: 9 },
        { title: 'Professional Cinematography', titleAr: 'التصوير الاحترافي', lessons: 9 },
        { title: 'Editing & Post-Production', titleAr: 'المونتاج والمعالجة', lessons: 9 },
        { title: 'Screenwriting', titleAr: 'كتابة السيناريو', lessons: 9 },
      ],
    },
    {
      id: 'c2',
      title: 'Acting Workshop with Hossam Dagher',
      titleAr: 'ورشة تمثيل مع حسام داغر',
      category: 'Workshop',
      level: 'Selective',
      instructor: 'Dr. Hossam Dagher',
      instructorId: 'i1',
      price: 6500,
      duration: '8 weeks',
      lectures: 16,
      enrolled: 38,
      rating: 4.9,
      tag: 'Interview Required',
      startDate: '2026-01-15',
      status: 'upcoming',
      cover: 'PRESENCE · EMOTION · CHARACTER',
      tint: '#d4a356',
      coverImage: 'https://scontent-lax3-2.xx.fbcdn.net/v/t39.30808-6/702343559_122282150876036919_7322111189426057606_n.jpg?stp=dst-jpg_s720x720_tt6&_nc_cat=100&ccb=1-7&_nc_sid=833d8c&_nc_ohc=MEDm5uY0hLsQ7kNvwHJn2Vj&_nc_oc=AdpyVZjS11NARYlkf4tMk8UJMINcBvNW_FVMDsf2vFdvA15KVf-av78v_uOYtLhKCxw&_nc_zt=23&_nc_ht=scontent-lax3-2.xx&_nc_gid=torgiEbb5XGD2Dd3TsLu5A&_nc_ss=72289&oh=00_Af73D3BmVMiT3q5ZLC0tcYG113FgfA_t2ceAnqgdWWBYGw&oe=6A1CDAEF',
      description: 'A selective acting workshop with the star Hossam Dagher — not your average acting class. This is a real turning point for anyone serious about entering the industry. Admission is selective: every applicant goes through a personal interview, and fees are only paid after acceptance. Graduates participate in a short film produced by the academy — a real starting point you can build on. Numbers are strictly limited and the selection is careful.',
      descriptionAr: 'ورشة تمثيل احترافية مع النجم حسام داغر — مش مجرد ورشة تمثيل، دي نقطة تحول حقيقية لأي حد قرر يدخل المجال بجد. الدخول مش متاح لكل المتقدمين: لازم تعدي مقابلة شخصية للقبول، وفي حالة القبول يتم دفع المصاريف. هتشارك في النهاية بفيلم قصير من إنتاج الأكاديمية — بداية فعلية تقدر تعتمد عليها. العدد محدود جدًا والاختيار بيتم بعناية.',
      requirements: ['Personal interview', 'Payment only after acceptance', 'Strictly limited seats'],
      includes: ['Short film produced by the academy', 'SOIC certificate'],
      modules: [
        { title: 'Camera presence & confidence', titleAr: 'الوقوف قدام الكاميرا بثقة', lessons: 4 },
        { title: 'Emotional truth & delivery', titleAr: 'التحكم في المشاعر وتوصيلها بصدق', lessons: 4 },
        { title: 'Building a character', titleAr: 'بناء الشخصية بشكل احترافي', lessons: 4 },
        { title: 'Short film production', titleAr: 'إنتاج الفيلم القصير', lessons: 4 },
      ],
    },
    {
      id: 'c3',
      title: 'Underwater Cinematography with Mazen Saeed',
      titleAr: 'التصوير تحت المياه مع مازن سعيد',
      category: 'Workshop',
      level: 'Advanced',
      instructor: 'Mazen Saeed',
      instructorId: 'i2',
      price: 14000,
      duration: '3 weeks intensive',
      lectures: 9,
      enrolled: 12,
      rating: 5.0,
      tag: 'First in Egypt & Arab World',
      startDate: '2026-02-04',
      status: 'upcoming',
      cover: 'UNDERWATER · DIVE · LICENSED',
      tint: '#3a8fb3',
      coverImage: 'https://scontent-lga3-3.xx.fbcdn.net/v/t39.30808-6/565702729_122257261232036919_6691075596840484666_n.jpg?stp=dst-jpg_s590x590_tt6&_nc_cat=102&ccb=1-7&_nc_sid=833d8c&_nc_ohc=2qeguskpEcoQ7kNvwG1BJdW&_nc_oc=AdoUn3AADtu37cSvOJONBTctcsg6X6D4FhrCtUSPceyi0OrBL21RgXwJC7tOj9ufXs8&_nc_zt=23&_nc_ht=scontent-lga3-3.xx&_nc_gid=hRO4h4nqh4xRdFGXC47vXA&_nc_ss=72289&oh=00_Af5Eu1cKoDlSCq8izawhKzFIGQqWjh0GFx3EHrzpKJZ5mQ&oe=6A1CDB4F',
      description: 'For the first time in Egypt and the Arab World — SOIC presents an experience like no other. An underwater photography workshop in partnership with director of photography and director Mazen Saeed, alongside the best professional team teaching diving and underwater cinematography. You\u2019ll learn how to film a cinematic scene in a different world full of color, movement, and light — at a professional level. You leave the workshop with a recognized diving license and a professional certificate. Seats are very limited.',
      descriptionAr: 'لأول مرة في مصر والوطن العربي — مدرسة السينما SOIC بتقدم تجربة مش زي أي تجربة. ورشة تصوير تحت المياه بالتعاون مع مدير التصوير والمخرج مازن سعيد وأفضل فريق محترف في تعليم الغوص والتصوير تحت الماء. هتتعلم إزاي تصوّر مشهد سينمائي وسط عالم تاني مليان ألوان وحركة وضوء بطريقة احترافية. هتخرج من الورشة بترخيص غوص معتمد وشهادة احترافية. العدد محدود جدًا.',
      includes: ['Certified diving license', 'SOIC professional certificate', 'On-location dive shoot'],
      modules: [
        { title: 'Dive safety & certification', titleAr: 'سلامة الغوص والترخيص', lessons: 3 },
        { title: 'Underwater camera systems', titleAr: 'منظومات التصوير تحت الماء', lessons: 3 },
        { title: 'Lighting & color underwater', titleAr: 'الإضاءة والألوان تحت الماء', lessons: 3 },
      ],
    },
    {
      id: 'c4',
      title: 'Screenwriting Intensive',
      titleAr: 'كتابة السيناريو',
      category: 'Short Course',
      level: 'Beginner',
      instructor: 'Yara Mansour',
      instructorId: 'i3',
      price: 3200,
      duration: '6 weeks',
      lectures: 12,
      enrolled: 87,
      rating: 4.7,
      tag: 'Online',
      startDate: '2025-12-02',
      status: 'live',
      cover: 'STORY · STRUCTURE · DIALOGUE',
      tint: '#9b6ee0',
      coverImage: 'https://scontent-atl3-3.xx.fbcdn.net/v/t39.30808-6/597850947_122264393048036919_3310807527125903131_n.jpg?stp=dst-jpg_p526x296_tt6&_nc_cat=108&ccb=1-7&_nc_sid=833d8c&_nc_ohc=Fg-eisd6YR4Q7kNvwGnr9Cw&_nc_oc=AdrA7BZ94rzEY_EepdmQpfl9nE35zudaEoWoAkyEBShVNr5UiYqbKg36EM5ohPcVxkQ&_nc_zt=23&_nc_ht=scontent-atl3-3.xx&_nc_gid=FQN5cWq-16zRAIbwW-AO0w&_nc_ss=72289&oh=00_Af7kmPVhg07ZJwAFRGNoasFIozs-EdAV0vWmPLJIIMXGsQ&oe=6A1CEF52',
      description: 'A focused short course on the craft of screenwriting — story structure, character arcs, and dialogue that sounds real. Weekly assignments with personal feedback. Ideal as a standalone course or as preparation for the full Filmmaking Diploma.',
      descriptionAr: 'كورس قصير ومركّز على فن كتابة السيناريو — بنية القصة، تطور الشخصيات، وحوار يحس بالواقع. واجبات أسبوعية بفيدباك شخصي. مناسب كـ كورس مستقل أو تجهيز لدبلومة صناعة الأفلام.',
      modules: [
        { title: 'Story & structure', titleAr: 'الحكاية والبنية', lessons: 3 },
        { title: 'Character & arcs', titleAr: 'الشخصية والتطور', lessons: 3 },
        { title: 'Dialogue that breathes', titleAr: 'حوار حي', lessons: 3 },
        { title: 'Workshopping a short', titleAr: 'ورشة فيلم قصير', lessons: 3 },
      ],
    },
    {
      id: 'c5',
      title: 'Editing on DaVinci Resolve',
      titleAr: 'مونتاج على دافنشي ريزولف',
      category: 'Short Course',
      level: 'All Levels',
      instructor: 'Karim Adel',
      instructorId: 'i4',
      price: 4500,
      duration: '5 weeks',
      lectures: 10,
      enrolled: 64,
      rating: 4.8,
      tag: 'Hands-on',
      startDate: '2026-01-08',
      status: 'upcoming',
      cover: 'CUT · COLOR · DELIVER',
      tint: '#e07a5f',
      coverImage: 'https://scontent-atl3-2.xx.fbcdn.net/v/t51.71878-10/591047222_1683258829303147_4886114029856101058_n.jpg?stp=dst-jpg_s960x960_tt6&_nc_cat=100&ccb=1-7&_nc_sid=5fad0e&_nc_ohc=AhJt2bS6B-8Q7kNvwFkK-mD&_nc_oc=Ado9_RFGXjMaaJoFFJTC0YEPaJ9aTITAP930rpHArGRay23O0PS-unlcK3euraRNpIM&_nc_zt=23&_nc_ht=scontent-atl3-2.xx&_nc_gid=FQN5cWq-16zRAIbwW-AO0w&_nc_ss=72289&oh=00_Af5LvciNGwKhzgRudtFXl4BUcx693aAMG5MAnbx_8wbhrg&oe=6A1CC858',
      description: 'Professional editing workflows on DaVinci Resolve, from rough assembly to color grading and final delivery. Lifts the editing module out of the full diploma for students who want to focus on post.',
      descriptionAr: 'سير عمل احترافي للمونتاج على DaVinci Resolve، من التجميع الأولي للتدرج اللوني وحتى التسليم النهائي. بياخد مادة المونتاج من الدبلومة لأي حد عايز يركز على ما بعد الإنتاج.',
      modules: [
        { title: 'Project setup & assembly', titleAr: 'إعداد المشروع والتجميع', lessons: 3 },
        { title: 'Cut & rhythm', titleAr: 'القطع والإيقاع', lessons: 3 },
        { title: 'Color grading', titleAr: 'التدرج اللوني', lessons: 2 },
        { title: 'Delivery & finishing', titleAr: 'التسليم والإنهاء', lessons: 2 },
      ],
    },
    {
      id: 'c6',
      title: 'Directing Masterclass',
      titleAr: 'ماستركلاس الإخراج',
      category: 'Workshop',
      level: 'Intermediate',
      instructor: 'SOIC Faculty',
      instructorId: 'i5',
      price: 5800,
      duration: '4 weeks',
      lectures: 8,
      enrolled: 0,
      rating: 0,
      tag: 'Coming Soon',
      startDate: '2026-03-01',
      status: 'planned',
      cover: 'VISION · BLOCKING · PERFORMANCE',
      tint: '#4ad287',
      coverImage: 'https://scontent-lga3-2.xx.fbcdn.net/v/t15.5256-10/590418602_1799099507406018_8982981386375301180_n.jpg?stp=dst-jpg_s960x960_tt6&_nc_cat=100&ccb=1-7&_nc_sid=5fad0e&_nc_ohc=jBUq1n5AODgQ7kNvwFekcWu&_nc_oc=AdrzOnf9n10LVTuJw1BUcWe47rSzxBuLwSBx97p5EU22gbT_MifsxlKUzhZ1xWuU4Wk&_nc_zt=23&_nc_ht=scontent-lga3-2.xx&_nc_gid=hRO4h4nqh4xRdFGXC47vXA&_nc_ss=72289&oh=00_Af47aNFukjUyt3-fcgINAy3zcGhnNGAnWvlPbNVXAP3n9A&oe=6A1CEDD9',
      description: 'A condensed directing masterclass: developing a director\u2019s eye, blocking for camera, working with actors, and shaping performance on set. Pulls the directing module of the diploma forward for working professionals who can\u2019t commit to the full 3-month program.',
      descriptionAr: 'ماستركلاس مكثف في الإخراج: تطوير رؤية المخرج، الـ blocking والكاميرا، الشغل مع الممثلين، وتشكيل الأداء على المنصة. بيقدم محتوى الإخراج من الدبلومة لأي محترف ما يقدرش يلتزم بالـ 3 شهور كاملة.',
      modules: [
        { title: 'The director\u2019s eye', titleAr: 'عين المخرج', lessons: 2 },
        { title: 'Blocking & camera', titleAr: 'الـ Blocking والكاميرا', lessons: 2 },
        { title: 'Working with actors', titleAr: 'الشغل مع الممثلين', lessons: 2 },
        { title: 'On-set performance', titleAr: 'الأداء على المنصة', lessons: 2 },
      ],
    },
  ],

  // student's enrolled + wishlist
  myEnrolled: ['c1', 'c4'],
  myWishlist: ['c3', 'c5'],

  schedule: [
    { id: 's1', courseId: 'c1', title: 'Camera Movement & Blocking', date: '2025-12-08', time: '19:00', duration: 90, status: 'upcoming-soon' },
    { id: 's2', courseId: 'c4', title: 'Three-act vs. Save the Cat', date: '2025-12-09', time: '20:00', duration: 60, status: 'upcoming' },
    { id: 's3', courseId: 'c1', title: 'Lens Choices & Depth of Field', date: '2025-12-11', time: '19:00', duration: 90, status: 'upcoming' },
    { id: 's4', courseId: 'c4', title: 'Writing the Inciting Incident', date: '2025-12-12', time: '20:00', duration: 60, status: 'upcoming' },
    { id: 's5', courseId: 'c1', title: 'Lighting for Mood', date: '2025-12-15', time: '19:00', duration: 90, status: 'upcoming' },
    { id: 's6', courseId: 'c4', title: 'Subtext & Dialogue', date: '2025-12-16', time: '20:00', duration: 60, status: 'upcoming' },
  ],

  recordings: [
    { id: 'r1', courseId: 'c1', title: 'Welcome & Course Overview', date: '2025-11-24', duration: '01:24:18', watched: 100 },
    { id: 'r2', courseId: 'c1', title: 'Visual Storytelling Foundations', date: '2025-11-27', duration: '01:38:42', watched: 100 },
    { id: 'r3', courseId: 'c1', title: 'The Director\u2019s Eye', date: '2025-12-01', duration: '01:52:10', watched: 64 },
    { id: 'r4', courseId: 'c1', title: 'Scene Geometry', date: '2025-12-04', duration: '01:41:05', watched: 22 },
    { id: 'r5', courseId: 'c4', title: 'Why Story Matters', date: '2025-11-25', duration: '01:08:31', watched: 100 },
    { id: 'r6', courseId: 'c4', title: 'Character Wants vs. Needs', date: '2025-12-02', duration: '01:12:44', watched: 78 },
  ],

  notes: [
    { id: 'n1', recordingId: 'r2', timestamp: '12:48', text: 'Frame rule of thirds — always leave room in the direction of motion.' },
    { id: 'n2', recordingId: 'r2', timestamp: '34:02', text: 'A "good" shot is one that answers a question the audience just asked.' },
    { id: 'n3', recordingId: 'r2', timestamp: '58:30', text: 'Keep a shot log on set — even quick scribbles save hours in edit.' },
    { id: 'n4', recordingId: 'r3', timestamp: '08:15', text: 'Watch how directors hide cuts. Most "long takes" are stitched.' },
    { id: 'n5', recordingId: 'r6', timestamp: '15:20', text: 'Want is conscious. Need is unconscious. The arc is when they switch.' },
  ],

  payments: [
    { id: 'p1', user: 'Mahmoud Saleh', userId: 'u3', course: 'Filmmaking Diploma', courseId: 'c1', amount: 8400, method: 'InstaPay', status: 'pending', date: '2025-12-04', ref: 'IPN-8842' },
    { id: 'p2', user: 'Salma Ahmed', userId: 'u4', course: 'Screenwriting Intensive', courseId: 'c4', amount: 3200, method: 'Card', status: 'approved', date: '2025-12-03', ref: 'CC-1129' },
    { id: 'p3', user: 'Youssef Nabil', userId: 'u5', course: 'Underwater Cinematography', courseId: 'c3', amount: 14000, method: 'InstaPay', status: 'pending', date: '2025-12-04', ref: 'IPN-8843' },
    { id: 'p4', user: 'Reem Magdy', userId: 'u6', course: 'Acting Workshop', courseId: 'c2', amount: 6500, method: 'Card', status: 'approved', date: '2025-12-02', ref: 'CC-1128' },
    { id: 'p5', user: 'Tarek Said', userId: 'u7', course: 'Editing on DaVinci Resolve', courseId: 'c5', amount: 4500, method: 'InstaPay', status: 'refund-requested', date: '2025-11-28', ref: 'IPN-8801' },
  ],

  users: [
    { id: 'u1', name: 'Layla Khalid', email: 'layla@example.com', role: 'student', joined: '2025-09-12', enrolled: 2, status: 'active' },
    { id: 'u2', name: 'Ahmed Farouk', email: 'ahmed.f@example.com', role: 'student', joined: '2025-10-04', enrolled: 1, status: 'active' },
    { id: 'u3', name: 'Mahmoud Saleh', email: 'm.saleh@example.com', role: 'student', joined: '2025-12-01', enrolled: 0, status: 'pending-payment' },
    { id: 'u4', name: 'Salma Ahmed', email: 'salma@example.com', role: 'student', joined: '2025-11-30', enrolled: 1, status: 'active' },
    { id: 'u5', name: 'Youssef Nabil', email: 'y.nabil@example.com', role: 'student', joined: '2025-12-02', enrolled: 0, status: 'pending-payment' },
    { id: 'u6', name: 'Reem Magdy', email: 'reem.m@example.com', role: 'student', joined: '2025-11-28', enrolled: 1, status: 'active' },
    {
      id: 'i1', name: 'Dr. Hossam Dagher', nameAr: 'د. حسام داغر',
      email: 'hossam@soic.eg', role: 'instructor', joined: '2025-06-01', status: 'active', courses: ['c1', 'c2'],
      title: 'Actor · Acting Coach · Cinema Faculty', titleAr: 'ممثل · مدرّب تمثيل · أستاذ سينما',
      tint: '#d4a356',
      yearsExp: 18, credits: 24, studentsAllTime: 320, rating: 4.9,
      bio: 'A working actor and Cinema Institute faculty member, Hossam Dagher leads SOIC\u2019s flagship Acting Workshop and the directing modules of the Filmmaking Diploma. His sessions are selective — every student earns their seat through a personal interview — and end with a real short film produced by the academy.',
      bioAr: 'ممثل شغّال وعضو هيئة تدريس بمعهد السينما، يقود د. حسام داغر ورشة التمثيل الرئيسية في SOIC ومحاضرات الإخراج في دبلومة صناعة الأفلام. ورشاته انتقائية — كل طالب يدخل بمقابلة شخصية — وتنتهي بفيلم قصير حقيقي من إنتاج الأكاديمية.',
      specialties: ['On-camera performance', 'Character work', 'Directing actors'],
    },
    {
      id: 'i2', name: 'Mazen Saeed', nameAr: 'مازن سعيد',
      email: 'mazen@soic.eg', role: 'instructor', joined: '2025-09-15', status: 'active', courses: ['c3'],
      title: 'Director of Photography · Director', titleAr: 'مدير تصوير · مخرج',
      tint: '#3a8fb3',
      yearsExp: 14, credits: 31, studentsAllTime: 48, rating: 5.0,
      bio: 'Director of photography and director Mazen Saeed leads SOIC\u2019s first-of-its-kind Underwater Cinematography workshop in Egypt and the Arab World. Combining a working DOP\u2019s eye with certified dive instruction, he turns a hostile environment into a usable cinema location.',
      bioAr: 'مدير التصوير والمخرج مازن سعيد يقود ورشة التصوير تحت المياه — الأولى من نوعها في مصر والوطن العربي. بيجمع بين عين مدير تصوير محترف وتعليم غوص معتمد عشان يحوّل عالم مليان تحديات إلى موقع تصوير حقيقي.',
      specialties: ['Underwater cinematography', 'Naturalistic lighting', 'Long-form camera work'],
    },
    {
      id: 'i3', name: 'Yara Mansour', nameAr: 'يارا منصور',
      email: 'yara@soic.eg', role: 'instructor', joined: '2025-10-20', status: 'active', courses: ['c4'],
      title: 'Screenwriter', titleAr: 'كاتبة سيناريو',
      tint: '#9b6ee0',
      yearsExp: 9, credits: 12, studentsAllTime: 187, rating: 4.7,
      bio: 'Yara Mansour writes for film and television, with credits across both indie shorts and prime-time drama. Her SOIC Screenwriting Intensive is built around weekly assignments with personal feedback — small group, close attention.',
      bioAr: 'يارا منصور كاتبة سيناريو للسينما والتلفزيون، بأعمال تشمل أفلام قصيرة مستقلة ومسلسلات بالموسم الذروة. كورس كتابة السيناريو في SOIC مبني على واجبات أسبوعية بفيدباك شخصي — مجموعات صغيرة واهتمام عن قرب.',
      specialties: ['Story structure', 'Character arcs', 'Dialogue'],
    },
    {
      id: 'i4', name: 'Karim Adel', nameAr: 'كريم عادل',
      email: 'karim@soic.eg', role: 'instructor', joined: '2025-07-12', status: 'active', courses: ['c5'],
      title: 'Editor · Colorist', titleAr: 'مونتير · مصحّح ألوان',
      tint: '#e07a5f',
      yearsExp: 11, credits: 40, studentsAllTime: 142, rating: 4.8,
      bio: 'Karim Adel cuts features, commercials, and series on DaVinci Resolve. His SOIC short course pulls the editing module of the Diploma forward — from rough assembly to color grading and final delivery — for students who want to focus on post.',
      bioAr: 'كريم عادل بيمنتج أفلام وإعلانات ومسلسلات على DaVinci Resolve. كورسه في SOIC بياخد مادة المونتاج من الدبلومة لأي حد عايز يركز على ما بعد الإنتاج — من التجميع الأولي للتدرج اللوني وحتى التسليم.',
      specialties: ['Editing', 'Color grading', 'DaVinci Resolve'],
    },
    {
      id: 'i5', name: 'SOIC Faculty', nameAr: 'هيئة تدريس SOIC',
      email: 'faculty@soic.eg', role: 'instructor', joined: '2025-05-01', status: 'active', courses: ['c6'],
      title: 'Cinema Institute Faculty', titleAr: 'أعضاء هيئة معهد السينما',
      tint: '#4ad287',
      yearsExp: 20, credits: 80, studentsAllTime: 250, rating: 4.9,
      bio: 'A rotating panel of Cinema Institute faculty who lead the directing masterclass and senior modules of the Filmmaking Diploma. Real teaching, from inside the industry.',
      bioAr: 'مجموعة من أعضاء هيئة تدريس معهد السينما يقودون ماستركلاس الإخراج والمحاضرات المتقدمة في دبلومة صناعة الأفلام. تعليم حقيقي من قلب الصناعة.',
      specialties: ['Directing', 'Cinematic vision', 'Production workflow'],
    },
    {
      id: 'i6', name: 'Nour El-Din', email: 'nour@example.com', role: 'instructor', joined: '2025-12-03', enrolled: 0, status: 'pending-approval', courses: [],
      title: 'Producer · Pending review', tint: '#888',
    },
    { id: 'a1', name: 'Admin Ops', email: 'ops@soic.eg', role: 'admin', joined: '2025-01-01', status: 'active', adminRole: 'Super Admin' },
    { id: 'a2', name: 'Maya Adel', email: 'maya@soic.eg', role: 'admin', joined: '2025-05-12', status: 'active', adminRole: 'Payments Manager' },
    { id: 'a3', name: 'Sherif Galal', email: 'sherif@soic.eg', role: 'admin', joined: '2025-08-04', status: 'active', adminRole: 'Content Moderator' },
  ],

  pendingCourses: [
    { id: 'pc1', title: 'Documentary Filmmaking', instructor: 'Yara Mansour', submitted: '2025-12-03', lectures: 14, price: 5200 },
    { id: 'pc2', title: 'Cinematic Color Grading', instructor: 'Karim Adel', submitted: '2025-12-04', lectures: 8, price: 3900 },
  ],

  adminRoles: [
    { id: 'r1', name: 'Super Admin', members: 1, color: 'gold', permissions: { courses: 'full', payments: 'full', users: 'full', content: 'full', refunds: 'full', analytics: 'full' } },
    { id: 'r2', name: 'Payments Manager', members: 2, color: 'accent', permissions: { courses: 'none', payments: 'full', users: 'read', content: 'none', refunds: 'full', analytics: 'read' } },
    { id: 'r3', name: 'Content Moderator', members: 1, color: 'success', permissions: { courses: 'edit', payments: 'none', users: 'read', content: 'full', refunds: 'none', analytics: 'none' } },
    { id: 'r4', name: 'Read-Only Analyst', members: 0, color: 'muted', permissions: { courses: 'read', payments: 'read', users: 'read', content: 'read', refunds: 'read', analytics: 'read' } },
  ],

  // Live lecture chat & participants
  liveParticipants: [
    { id: 'u1', name: 'Layla Khalid', isMuted: true, isHandRaised: false, role: 'student' },
    { id: 'u2', name: 'Ahmed Farouk', isMuted: true, isHandRaised: true, role: 'student' },
    { id: 'u4', name: 'Salma Ahmed', isMuted: false, isHandRaised: false, role: 'student' },
    { id: 'u6', name: 'Reem Magdy', isMuted: true, isHandRaised: false, role: 'student' },
    { id: 'u8', name: 'Karim Saber', isMuted: true, isHandRaised: false, role: 'student' },
    { id: 'u9', name: 'Nada Helmy', isMuted: true, isHandRaised: true, role: 'student' },
    { id: 'u10', name: 'Hassan Tarek', isMuted: true, isHandRaised: false, role: 'student' },
    { id: 'u11', name: 'Mona Selim', isMuted: false, isHandRaised: false, role: 'student' },
  ],

  liveChat: [
    { id: 1, user: 'Layla Khalid', message: 'Joining from Alexandria 👋', time: '19:02' },
    { id: 2, user: 'Ahmed Farouk', message: 'Will the slides be shared after?', time: '19:04' },
    { id: 3, user: 'Salma Ahmed', message: 'The shot examples look great', time: '19:11' },
    { id: 4, user: 'Reem Magdy', message: 'Could you go over framing once more?', time: '19:18' },
  ],

  analytics: {
    revenue30d: 184200,
    revenuePrev: 142800,
    newStudents: 47,
    activeCourses: 5,
    completionRate: 73,
    revenueChart: [12, 18, 14, 22, 19, 26, 28, 24, 30, 32, 28, 35, 38, 34],
    enrollmentChart: [3, 5, 4, 6, 4, 7, 8, 6, 9, 11, 8, 12, 10, 14],
  },
};

export const fmtEGP = (n) => 'EGP ' + n.toLocaleString();
export const fmtDate = (iso) => {
  const d = new Date(iso);
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
};
export const fmtShortDate = (iso) => {
  const d = new Date(iso);
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
};
export const initials = (name) => name.split(' ').map(p => p[0]).slice(0, 2).join('').toUpperCase();
